### ISSUE TITLE
Incorrect handling of errors.

### ISSUE THREAD

**Issue by josemesona** [josemesona/ManagedDism#1]
### [Copied from CodePlex](https://manageddism.codeplex.com/workitem/1282)
# 

It might be the case that my issue report is incorrect but hopefully it is and you'll find it useful.

I spent some time trying to figure out why EnableFeature keeps returning an error. I dig into code and I saw that hr from EnableFeature function returns 1 (that is 0x1). It was quite vague and strange to me because HRESULTS are usually long numbers (like 0x8001012E). 

I tried to look up what 0x1 means and found this website http://codeswamp.tolon.co.uk/codeswamp_00000001.html where one of the meaning is S_FALSE

According to MSDN and Dism reference, S_FALSE is also Success(sic!). 
https://msdn.microsoft.com/en-us/library/windows/desktop/ms688560(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/hh824754.aspx
Returns S_OK or S_FALSE on success.
Therefore I think that this line does not apply
// See if the call failed
if (hr != 0)
Microsoft defines FAILED as hr < 0 and SUCCESS as hr >= 0 according to
https://msdn.microsoft.com/en-us/library/windows/desktop/ms693474(v=vs.85).aspx

Can you confirm this bug?

thx

**Comment by josemesona** [comment]
The documentation for [EnableFeature](https://msdn.microsoft.com/en-us/library/windows/desktop/hh824737(v=vs.85).aspx) says

> #### Return value
returns ``` S_OK ``` on success.

Which implies that the method only succeeded if it returns zero.  If anyone can prove otherwise, we should definitely update the logic.

**Comment by josemesona** [comment]
I've at least centralized the failure detection logic so that we can change it one place if necessary

**Comment by jeffkl** [comment]
Fixed by #22
