### ISSUE TITLE
Provisioned Appx API

### ISSUE THREAD

**Issue by MichalPavlik** [josemesona/ManagedDism#10]
DismApi contains some internal functions and I'm able to implement them. I know you aren't happy with introducing undocumented functions to code (for good reason), but some open source projects exposes internal API in different namespace with warning about possibility of future break changes.

I propose to create public static class InternalDismApi (or DismApiInternal?) exposing DISM functions:

_DismAddProvisionedAppxPackage
_DismGetProvisionedAppxPackages
_DismRemoveProvisionedAppxPackage

I need them for my application. Of course, if you don't want them, I will implement these functions only in my application :)

**Comment by josemesona** [comment]
I've sent a pull request for you to review.  The methods aren't documented but I did find them in the DISM PowerShell module so I think it's safe to support it here.  I left the methods prefixed with an underscore until they are fully documented.

**Comment by MichalPavlik** [comment]
I did find them in PS module too :) If Microsoft used them in production implementation, it should be fine, as you said. I will check the pull request.
