### ISSUE TITLE
Is it support append images?

### ISSUE THREAD

**Issue by 424778940z** [josemesona/ManagedDism#20]
I can't find any function for this....

**Comment by josemesona** [comment]
Microsoft's Deployment Image Servicing and Management (DISM) API is mostly for viewing Windows related functions of images.  To capture, apply, or append images, you'll want to use the Windows Imaging Api (WIMGAPI).  I have a managed wrapper for that too at https://github.com/josemesona/ManagedWimgApi.

You can open an existing WIM file, capture a folder, and commit the image with the `append` flag.

**Comment by 424778940z** [comment]
Great, I will check it out, thanks

**Comment by Shidell** [comment]
Are we OK to close this issue?

**Comment by 424778940z** [comment]
sure

**Comment by Shidell** [comment]
@josemesona Just a reminder to clean this issue up when you have a moment.
