### ISSUE TITLE
Unable to commit image with DismApi.UnmountImage and "commitChange" set to true

### ISSUE THREAD

**Issue by o-leave** [josemesona/ManagedDism#24]
Hi,
I probably pass next something but every time i try to commit changes made on a WIM file, i get an error "wrong parameter" / "Paramètre incorrect".

There maybe a solution to get more verbose logs ?

Best regards.

**Comment by Shidell** [comment]
The error is on line 1310 of DismApi.cs. It is as follows:

`            var flags = commitChanges ? DismApi.DISM_COMMIT_MASK : DismApi.DISM_DISCARD_IMAGE;`

DISM_COMMIT_MASK is 0xFFFF0000, which is invalid. The correct flag is DISM_COMMIT_IMAGE, which is 0x00000000. 

Correct line 1310 to the following:

`            var flags = commitChanges ? DismApi.DISM_COMMIT_IMAGE : DismApi.DISM_DISCARD_IMAGE;`
