### ISSUE TITLE
Strong naming

### ISSUE THREAD

**Issue by Kaon68** [josemesona/ManagedDism#28]
Hello

Is it possible to strong name your assembly (sign it, even with a dev snk) ? A strong named assembly require all its references are strong named :-/

Thanks :)

**Comment by Akzentianer** [comment]
Hello Shidell,
even this thread is open for a while, I want to add myself to list of people who would appreciate a strong named dll.

Kind regards

**Comment by Shidell** [comment]
@Kaon68, @Akzentianer Is bypassing the Signature Verification an option?

https://docs.microsoft.com/en-us/dotnet/framework/app-domains/create-and-use-strong-named-assemblies

> tarting with the .NET Framework 3.5 Service Pack 1, strong-name signatures are not validated when an assembly is loaded into a full-trust application domain, such as the default application domain for the MyComputer zone. This is referred to as the strong-name bypass feature. In a full-trust environment, demands for StrongNameIdentityPermission always succeed for signed, full-trust assemblies, regardless of their signature. The strong-name bypass feature avoids the unnecessary overhead of strong-name signature verification of full-trust assemblies in this situation, allowing the assemblies to load faster. +

The bypass feature applies to any assembly that is signed with a strong name and that has the following characteristics:

Fully trusted without StrongName evidence (for example, has MyComputer zone evidence).

Loaded into a fully trusted AppDomain.

Loaded from a location under the ApplicationBase property of that AppDomain.

Not delay-signed.

**Comment by Kaon68** [comment]
hi

look at this : https://github.com/dsplaisted/strongnamer

**Comment by Akzentianer** [comment]
I tested this strongnamer project an it works but if you want to debug this the pdb will not be found.
If the dll is directly strong named the pdb is created based on this so the visual studio debugger will find and recognize the pdb.

Kind regards
