### ISSUE TITLE
error message with AddPackage

### ISSUE THREAD

**Issue by ShirleyYH** [josemesona/ManagedDism#39]
Hello 
I use DismApi.AddPackage Function to Add Msu File.
I tried two cases to add package .
The first one is 184MB ,and it was successful. 
The second is 1.2GB then I got the error message like this:

Unhandled Exception: Microsoft.Dism.DismReloadImageSessionRequiredException: A reload of image session is required.

Do you have any idea about this problem? Please help me to solve this problem.
Thanks!

**Comment by Shidell** [comment]
Have you tried closing the existing session (from adding the 184MB package), and opening a new session, and then adding the 1.2GB package?

**Comment by ShirleyYH** [comment]
Hi Shidell,
Two case executed separately. Each case only add one package.
I did not add 184MB Package after add 1.2GB Package .

**Comment by Shidell** [comment]
Which Package is failing? (What is the 1.2GB Package?)

What other testing have you done?

Have you tried other Packages, or the same Package on other Operating Systems or Architectures?

**Comment by ShirleyYH** [comment]
I want to add "windows-10-update-kb4057142" this package.

I try to add  respectively different size of the package,:
1.Adding "windows-10-update-kb4053579" cumulative update package(size 1.16GB) is failling.
2.Adding "windows-10-update-kb4057142" cumulative update package(size 1.2GB) is failling.
3.Adding "windows-10-update-kb4056890" Incremental update package(size 184MB) is success.

3 test results on 2 computers are the same. My computer are both Win10 X64 LTSB.
The code is as follows:

int imageIndex = 1;
DismApi.Initialize(DismLogLevel.LogErrors);
     try
     {               
          DismApi.MountImage(imagePath, mountPath, imageIndex);
               
          using (DismSession session = DismApi.OpenOfflineSession(mountPath))
           {
                DismApi.AddPackage(session, packageFilePath, false, false);
                DismApi.CommitImage(session, false);
                DismApi.CloseSession(session);
            }
            DismApi.UnmountImage(mountPath, true);
       }
       finally
       {
            DismApi.Shutdown();                
       }

**Comment by Shidell** [comment]
Good info, thanks for providing the cases. 

I've downloaded the same KB updates you referenced and have reproduced the error with KB 4053579, but that's all for now. I'll update further when I know more.

**Comment by Shidell** [comment]
@ShirleyYH Please see the changes referenced above; I've modified AddPackage to return DISM error codes (int), so it now supports adding packages that might indicate a session reload is required (instead of throwing an exception.)

In use, if you receive a return value of DIsmApi.DISMAPI_S_RELOAD_IMAGE_SESSION_REQUIRED, (as opposed to DismApi.ERROR_SUCCESS, or 0x0), simply be sure to reload the image session before continuing with any other image servicing work you need to do.

**Comment by ShirleyYH** [comment]
@Shidell  Thanks. I will wait the project merge to master.

**Comment by jeffkl** [comment]
In the latest version of the package (2.0.0), the session is now automatically reloaded.

https://github.com/josemesona/ManagedDism/commit/7ca682ae711464d669c14edcc35690970f0659f7
