### ISSUE TITLE
Jeff, have you become a new maintainer?

### ISSUE THREAD

**Issue by Shidell** [josemesona/ManagedDism#47]
Just wondering what's the state of this project, and if you might know more, given your activity.

**Comment by jeffkl** [comment]
Yeah sorry for falling off the face of the earth.  @josemesona is my non-work-related GitHub account.  I'm going to transfer my repos from josemesona to jeffkl so I can keep them up-to-date.  I've been busy working on MSBuild for the last year and haven't had time to contribute to my personal projects.

**Comment by Shidell** [comment]
Cool--no problem. Does that mean you're going to close this project and re-open it under the "Jeffkl" name, or will it remain here?

**Comment by jeffkl** [comment]
I'm going to transfer it which supposedly keeps all links in tact.

https://help.github.com/articles/about-repository-transfers/

Unless you have concerns.

**Comment by Shidell** [comment]
Nope, no concerns, just wondering where we'll find it going forward.

Thanks!
