### ISSUE TITLE
Fails to load the DISMAPI.DLL when prefer 32-bit is selected it the project settings

### ISSUE THREAD

**Issue by gbiellem** [josemesona/ManagedDism#5]
Tried using this in a pre-existing app that compiles as cpu-any with prefer 32-bit enabled.
The ManagedDism throws and indicates it can't find the DISMAPI.dll
Unticking prefer 32-bit rectifies it.

The test machine OS was Windows 10 Enterprise which has both 32 bit and 64 versions of the DLL so I was surprised it failed.

**Comment by josemesona** [comment]
This probably has something to do with how the .NET framework does platform invoke.  Do you have a 32-bit only machine where you can test ManagedDism.dll with "don't prefer 32-bit"?  If that works, then it'll be easy to update the assembly and consider this fixed.

**Comment by josemesona** [comment]
@gbiellem have you had a chance to test a change to the compile options of ManagedDism?

**Comment by MichalPavlik** [comment]
@gbiellem did you see the DISM log? I had this problem too when I tried open online session in x86 process. The log then contained entry:

_Running the DISM API online under WoW64 is not supported - DismOpenSessionInternal(hr:0x8007000b)_

So it seems as known limitation.

**Comment by josemesona** [comment]
@MichalPavlik did you try compiling with the "prefer 32-bit" flag off and running as an x86 process?  I'm hoping to fix this by changing the compile flags and then the managed DLL will work as a 32-bit or 64-bit process.  I wonder how the DISM PowerShell module is compiled...

**Comment by MichalPavlik** [comment]
@josemesona  i'm not sure that you can fix this. It's really a limitation of 64bit Windows. I just tried start 32bit cmd.exe (C:\Windows\SysWOW64\cmd.exe) and started DISM online session with this result:

> Microsoft Windows [Version 10.0.14393]
> (c) 2016 Microsoft Corporation. All rights reserved.
> 
> C:\WINDOWS\system32>dism /online /get-packages
> 
> Deployment Image Servicing and Management tool
> Version: 10.0.14393.0
> 
> 
> Error: 11
> 
> You cannot service a running 64-bit operating system with a 32-bit version of DISM.
> Please use the version of DISM that corresponds to your computer's architecture.
> 
> The DISM log file can be found at C:\WINDOWS\Logs\DISM\dism.log

Everything is OK without "Prefer 32-bit" flag. At least when you start the application from another 64bit process. Start AnyCPU application from 32bit process means, that the application is also compiled as 32bit. IIRC this behavior can be changed by CLR setting, but the flag is machine-wide.
