### ISSUE TITLE
How to enable IIS, CGI, ISAPI with DismAPI

### ISSUE THREAD

**Issue by bkpang** [josemesona/ManagedDism#6]
Hai sir,
I am currently using DISM.exe in my setup project to enable IIS, CGI, ISAPI and etc feature in IIS, I would like to use DISMAPI to complete this task, do you have any example to do this? can you provide me the sample on how to use DISMAPI.dll to do this?

**Comment by josemesona** [comment]
Are you trying to enable the feature in the current running instance of Windows or an offline .wim image?

**Comment by josemesona** [comment]
It should look something like this:

``` C#
string[] featureNames = new[] { "PackageA", "PackageB" };

DismApi.Initialize(DismLogLevel.LogErrors);

try
{
    // Enable feature for offline image
    //
    using (DismSession session = DismApi.OpenOfflineSession(@"C:\install.wim"))
    {
        foreach (string featureName in featureNames)
        {
            DismApi.EnableFeatureByPackageName(session, featureName, packageName: null, limitAccess: false, enableAll: true);
        }
    }

    // Enable feature for current Windows session
    //
    using (DismSession session = DismApi.OpenOnlineSession())
    {
        foreach (string featureName in featureNames)
        {
            DismApi.EnableFeatureByPackageName(session, featureName, packageName: null, limitAccess: false, enableAll: true);
        }
    }
}
finally
{
    DismApi.Shutdown();
}
```

You can always look at the [native samples](https://msdn.microsoft.com/en-us/library/windows/desktop/hh824804(v=vs.85).aspx) and this API should be very close.

**Comment by josemesona** [comment]
@bkpang have you had a chance to try this?

**Comment by josemesona** [comment]
I'm going to close this for now, let me know if you need more help.
