### ISSUE TITLE
Capabilities API

### ISSUE THREAD

**Issue by MichalPavlik** [josemesona/ManagedDism#7]
Can be Capabilities API added to library?

[DismGetCapabilities](https://msdn.microsoft.com/en-us/library/windows/desktop/mt684923(v=vs.85).aspx)
[DismGetCapabilityInfo](https://msdn.microsoft.com/en-us/library/windows/desktop/mt684924(v=vs.85).aspx)
[DismAddCapability](https://msdn.microsoft.com/en-us/library/windows/desktop/mt684919(v=vs.85).aspx)
[DismRemoveCapability](https://msdn.microsoft.com/en-us/library/windows/desktop/mt684925(v=vs.85).aspx)

Are pull requests allowed for this?

**Comment by josemesona** [comment]
Yes absolutely.  Pull requests are gladly accepted, I've opened up #8 so that I can remember to make a CONTRIBUTING.md.  Just fork the repo and send out the PR.  Feel free to contact me if you run into any issues.

**Comment by MichalPavlik** [comment]
OK, I hope it will be done this week. I never contributed to GitHub, so there may be some troubles :)

**Comment by josemesona** [comment]
You can follow the instructions under "Pull Request" here: https://guides.github.com/activities/contributing-to-open-source/#contributing

You basically:
1. Make a fork
2. Clone your fork
3. Create a branch
4. Make as many commits as you need
5. Push your branch to your fork
6. Send a pull request of your branch on your fork against this repo's master

Let me know how it goes!

**Comment by MichalPavlik** [comment]
It goes well so far. I successfully implemented DismGetCapabilities and DismGetCapabilityInfo yesterday. I'm using your conventions, but there are problems with XML documentation. For example [DismCapability](https://msdn.microsoft.com/en-us/library/windows/desktop/mt684921(v=vs.85).aspx) structure has incorrectly described parameters. Should I strictly use these descriptions or use custom, but more meaningful?

**Comment by josemesona** [comment]
Go ahead and keep the real documentation on the internal structs and extern native methods but feel free to improve the XML doc comments on the public facing method.

**Comment by josemesona** [comment]
Closed by #9
